//! Script to generate debug.parquet file with example addresses
//!
//! Run with: cargo run --bin generate_debug_parquet
use amp_core::parquet::build_local_parquet;
use amp_core::structs::LocalData;
use std::fs;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Generating debug.parquet with example addresses...");
    let debug_addresses = vec![
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21150".to_string()),
            adress: "Kornettsgatan 18C".to_string(),
            gata: Some("Kornettsgatan".to_string()),
            gatunummer: Some("18C".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21426".to_string()),
            adress: "Claesgatan 2B".to_string(),
            gata: Some("Claesgatan".to_string()),
            gatunummer: Some("2B".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21748".to_string()),
            adress: "Östra Kristinelundsvägen 27D".to_string(),
            gata: Some("Östra Kristinelundsvägen".to_string()),
            gatunummer: Some("27D".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21436".to_string()),
            adress: "Karlskronaplan 3".to_string(),
            gata: Some("Karlskronaplan".to_string()),
            gatunummer: Some("3".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21741".to_string()),
            adress: "Västra Rönneholmsvägen 76C".to_string(),
            gata: Some("Västra Rönneholmsvägen".to_string()),
            gatunummer: Some("76C".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21442".to_string()),
            adress: "Vitemöllegatan 11A".to_string(),
            gata: Some("Vitemöllegatan".to_string()),
            gatunummer: Some("11A".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21552".to_string()),
            adress: "Docentgatan 1B".to_string(),
            gata: Some("Docentgatan".to_string()),
            gatunummer: Some("1B".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21550".to_string()),
            adress: "Eriksfältsgatan 98B".to_string(),
            gata: Some("Eriksfältsgatan".to_string()),
            gatunummer: Some("98B".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21448".to_string()),
            adress: "Lantmannagatan 50 U1".to_string(),
            gata: Some("Lantmannagatan".to_string()),
            gatunummer: Some("50 U1".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: true,
            active: true,
            postnummer: Some("21238".to_string()),
            adress: "Pysslinggatan 4".to_string(),
            gata: Some("Pysslinggatan".to_string()),
            gatunummer: Some("4".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
        LocalData {
            valid: false,
            active: true,
            postnummer: Some("11111".to_string()),
            adress: "Låssasgatan 11A".to_string(),
            gata: Some("Låssasgatan".to_string()),
            gatunummer: Some("11A".to_string()),
            info: None,
            tid: None,
            dag: None,
            taxa: None,
            antal_platser: None,
            typ_av_parkering: None,
        },
    ];
    let buffer = build_local_parquet(debug_addresses)?;
    fs::write("android/assets/data/debug.parquet", &buffer)?;
    println!(
        "✓ Created android/assets/data/debug.parquet ({} bytes)",
        buffer.len()
    );
    Ok(())
}
