use std::collections::HashMap;
use std::sync::OnceLock;
/// Get or initialize the parking data cache
///
/// # Returns
/// Static reference to parking data HashMap
/// Result of address matching operation
/// Match user input address against static correlations from server
///
/// This checks if the provided address (street, street_number, postal_code) exists
/// in the pre-computed correlations generated by:
/// `cargo run --release -- output --android`
///
/// # Arguments
/// * `street` - Street name (e.g., "Storgatan")
/// * `street_number` - Street number (e.g., "10")
/// * `postal_code` - Postal code (e.g., "22100")
///
/// # Returns
/// MatchResult::Valid with address data if found, MatchResult::Invalid otherwise
/// Validate address input fields
///
/// Checks that all fields contain non-empty values after trimming whitespace.
///
/// # Arguments
/// * `street` - Street name
/// * `street_number` - Street number
/// * `postal_code` - Postal code
///
/// # Returns
/// true if all fields are non-empty, false otherwise
pub fn validate_input(street: &str, street_number: &str, postal_code: &str) -> bool {
    !street.trim().is_empty() && !street_number.trim().is_empty() && !postal_code.trim().is_empty()
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_validate_input() {
        assert!(validate_input("Storgatan", "10", "22100"));
        assert!(!validate_input("", "10", "22100"));
        assert!(!validate_input("Storgatan", "", "22100"));
        assert!(!validate_input("Storgatan", "10", ""));
    }
}
