[application]
name = "amp"
version = "1.0.0"
out_dir = "/home/albin/Documents/"
default_platform = "mobile"
asset_dir = "assets"

[bundle]
publisher = "Skäggbyrån Malmö"
identifier = "se.malmo.skaggbyran.amp"
icon = ["assets/icon/icon-512.png"]
resources = [
    "assets/style.css",
    "assets/fonts/**/*"
]

[bundle.ios]
publisher = "Skäggbyrån Malmö"
identifier = "se.malmo.skaggbyran.amp"
icon = ["assets/icon/icon-512.png"]
resources = [
    "assets/style.css",
    "assets/fonts/**/*"
]

[profile.ios-release]
inherits = "release"
opt-level = 3
strip = false
